# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: garapin-pos-engine-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: garapin-pos-engine
  template:
    metadata:
      labels:
        app: garapin-pos-engine
    spec:
      containers:
      - name: garapin-pos-engine
        image: garapin-pos-engine:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: NODE_ENV
          value: "production"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: garapin-pos-engine-service
spec:
  type: NodePort
  selector:
    app: garapin-pos-engine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30036